name: Docker
on: [push]
jobs:
  aws-sigv4-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: aws-sigv4-proxy
